### PR TITLE
Suggested updates.

### PR DESCRIPTION
**Pull request by nbonniere**
All other data is based on 'this_aircraft' data and time should be as well.

### CODE REVIEW

**Comment by lyusupov** [comment]
Both commits generally looks Ok to me.
It will take roughly few days to evaluate these proposed changes on my local OGN receiver, with both 'Region' settings.
As long as it does not break 'EU mode' - I basically don't care.

I am curious, why are you proposing to switch onto Pavel's new NA freq. hopping plan
while, I suppose, most of (few) N/S. America and Australia OGN receivers are still running 'old' binary code of the hopping algorithm? Is the 'new' algorithm compatible with 'old' one?

**Comment by nbonniere** [comment]
Pawel's new OGN code only changes frequency slot 2. Slot 1 is unaffected.
The OGN receiver doesn't hop to slot 2, so he made a change to the OGN frequency plan so that slot 2 of OGN falls within the bandwidth of the OGN receiver, so he can receive the second packet and thus improves the probability of receiving one or the other or both.

**Comment by lyusupov** [comment]
**Any other patches except related to the OGN topic will block or CANCEL processing of this PR entirely**.
Reasons were explained there: https://github.com/lyusupov/SoftRF/issues/58

**Comment by nbonniere** [comment]
For testing, I am using Pawel's v0.2.7 OGN receiver code, not v0.2.6.

**Comment by lyusupov** [comment]
Re-file
* 501fc52 and 124daf9 as PR-1
* 758799b as PR-2

**Pull request closed without merging**
